import { Injectable } from '@nestjs/common';
import * as puppeteer from 'puppeteer';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class PdfGeneratorService {
  private uploadDir = path.join(process.cwd(), 'uploads', 'catalogs');

  constructor() {
    if (!fs.existsSync(this.uploadDir)) {
      fs.mkdirSync(this.uploadDir, { recursive: true });
    }
  }

  async generateCatalogPdf(catalog: any): Promise<string> {
    const browser = await puppeteer.launch({ headless: true });
    const page = await browser.newPage();

    const html = this.buildHtml(catalog);
    await page.setContent(html, { waitUntil: 'load' });

    const filePath = path.join(this.uploadDir, `${catalog.id}.pdf`);
    await page.pdf({
      path: filePath,
      format: 'A4',
      printBackground: true,
      margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' },
    });

    await browser.close();
    return filePath;
  }

  getPdfUrl(catalogId: string): string {
    return `/uploads/catalogs/${catalogId}.pdf`;
  }

  private buildHtml(catalog: any): string {
    const items = catalog.items || [];
    const vendorName = catalog.vendor?.companyName || catalog.vendor?.firstName || 'WholesaleX Pro';

    const rows = items.map((item: any, index: number) => {
      const p = item.product;
      const price = item.customPrice ? item.customPrice : p.unitPrice;
      const tierRows = (p.tierPrices || []).map((tp: any) =>
        `<tr>
          <td>${tp.minQty}${tp.maxQty ? ` - ${tp.maxQty}` : '+'}</td>
          <td>₹${tp.price}</td>
        </tr>`
      ).join('');

      return `
        <div style="page-break-inside: avoid; margin-bottom: 20px; border: 1px solid #ddd; padding: 12px; border-radius: 6px;">
          <div style="display: flex; gap: 16px;">
            <div style="width: 100px; height: 100px; background: #f5f5f5; display: flex; align-items: center; justify-content: center; border-radius: 4px;">
              <span style="color: #999; font-size: 12px;">${p.thumbnail ? `<img src="${p.thumbnail}" style="width:100px;height:100px;object-fit:cover;border-radius:4px;"/>` : 'No Image'}</span>
            </div>
            <div style="flex: 1;">
              <h3 style="margin: 0 0 6px 0; font-size: 16px;">${index + 1}. ${p.title}</h3>
              <p style="margin: 0 0 6px 0; color: #666; font-size: 13px;">SKU: ${p.sku || 'N/A'} | MOQ: ${p.moq} | Vendor: ${p.vendorName || 'N/A'}</p>
              <p style="margin: 0 0 6px 0; font-size: 14px; font-weight: bold; color: #2563eb;">Price: ₹${price}</p>
              ${tierRows ? `<div style="margin-top: 8px;">
                <p style="margin: 0 0 4px 0; font-size: 12px; font-weight: bold;">Tier Pricing</p>
                <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
                  <thead><tr style="background: #f5f5f5;"><th style="text-align:left;padding:4px;border:1px solid #ddd;">Qty</th><th style="text-align:right;padding:4px;border:1px solid #ddd;">Price/unit</th></tr></thead>
                  <tbody>${tierRows}</tbody>
                </table>
              </div>` : ''}
            </div>
          </div>
        </div>
      `;
    }).join('');

    return `<!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${catalog.name}</title>
      <style>
        body { font-family: Arial, sans-serif; color: #333; line-height: 1.5; }
        .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 12px; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 22px; color: #1e40af; }
        .header p { margin: 4px 0 0 0; color: #666; font-size: 13px; }
        .footer { text-align: center; margin-top: 30px; padding-top: 12px; border-top: 1px solid #ddd; color: #999; font-size: 11px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${catalog.name}</h1>
        <p>${catalog.description || 'Digital Catalog'} | Vendor: ${vendorName}</p>
      </div>
      ${rows}
      <div class="footer">
        Generated by WholesaleX Pro | ${new Date().toLocaleDateString()}
      </div>
    </body>
    </html>`;
  }
}
